config/config.yaml

============================

Project Base Paths

============================

root_path: "F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/"   # Local repo root

mlb_data:
base_path:   "F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/data/sports/baseball/mlb/"
raw:         "F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/data/sports/baseball/mlb/raw"
api:         "F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/data/sports/baseball/mlb/data_sources/api"
test_output: "F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/test_output"

============================

API Endpoints

============================

api:
mlb:
pitcher:  "https://statsapi.mlb.com/api/v1/people/{pitcher_id}"
schedule: "https://statsapi.mlb.com/api/v1/schedule"
graphql:  "https://statsapi.mlb.com/graphql"
fangraphs:
base_url: "https://www.fangraphs.com/api"

============================

Model Configuration

============================

models:
mlb_rfi: 
features_config_path: "F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/src/models/sports/baseball/mlb/mlb-models/rfi_features_config.json"

============================

Defaults & Logging

============================

defaults:
lookback_days: 30   # Default lookback window for fetching games

logging:
level:   "INFO"
format:  "%(asctime)s — %(levelname)s — %(message)s"
datefmt: "%Y-%m-%d %H:%M:%S"

