# remove the “config/config.yaml” line entirely
# (start with your comments or the first actual setting)

# Top-level settings
root_path: 'F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/'
log_path: 'F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/logs'
cache_path: 'F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/.cache'


mlb_data:
  base_path:   'F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/data/sports/baseball/mlb/'
  raw:         data/sports/baseball/mlb/raw
  statcast:    data/sports/baseball/mlb/raw/statcast/statcast_{lookback}d_raw.csv
  api:         'F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/data/sports/baseball/mlb/data_sources/api'
  test_output: 'F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/test_output'
  season: 2025
  use_cache: true
  cache_dir: .cache
  team_abbrev_cds_cache_path: '.cache/team_codes_{season}.json'
  statcast:
    raw_csv: data/sports/baseball/mlb/raw/statcast_{lookback}d_raw.csv
    split_json: data/sports/baseball/mlb/processed/team_woba_{lookback}d.json
    combined_json: data/sports/baseball/mlb/processed/team_woba_splits_combined.json  

api:
  mlb:
    pitcher:  'https://statsapi.mlb.com/api/v1/people/{pitcher_id}'
    schedule: 'https://statsapi.mlb.com/api/v1/schedule'
    # …any other endpoints…

models:
  mlb_rfi:
    feature_definitions_path:  "F:/Dropbox/1_Work/Development/GitHub/Fluidity1337/ai-ml-predictive-models/config/features/mlb_rfi_features.json"

logging:
  version: 1
  disable_existing_loggers: False

  formatters:
    simple:
      format: "%(asctime)s — %(levelname)s — %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout

    file:
      class: logging.FileHandler
      level: DEBUG
      filename: logs/mlb_pipeline.log
      formatter: simple
      encoding: utf-8

  root:
    level: DEBUG
    handlers: [console, file]

